version: '3.7'
services:
 db:
   image: mysql:8.0.19
   command: '--default-authentication-plugin=mysql_native_password'
   restart: always
   volumes:
     - ./db_data:/var/lib/mysql
   environment:
     - MYSQL_ROOT_PASSWORD=somewordpress
     - MYSQL_DATABASE=wordpress
     - MYSQL_USER=wordpress
     - MYSQL_PASSWORD=wordpress
 wordpress:
   image: wordpress:latest
   ports:
     - 80:80
   restart: always
   volumes:
    - ./wp-content:/var/www/html/wp-content
   environment:
    - WORDPRESS_DB_HOST=db
    - WORDPRESS_DB_USER=wordpress
    - WORDPRESS_DB_PASSWORD=wordpress
    - WORDPRESS_DB_NAME=wordpress
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - 3333:80
  environment:
    PMA_HOST: db
    MYSQL_ROOT_PASSWORT: password
